applications:
  api-gateway:
    type: python:3.13
    source:
      root: /api-gateway
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true
    relationships:
      cpu-worker:
        service: "cpu-worker"
        endpoint: "http"
      memory-worker:
        service: "memory-worker"
        endpoint: "http"
      network-simulator:
        service: "network-simulator"
        endpoint: "http"

  cpu-worker:
    type: python:3.13
    source:
      root: /cpu-worker
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  memory-worker:
    type: python:3.13
    source:
      root: /memory-worker
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  network-simulator:
    type: python:3.13
    source:
      root: /network-simulator
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  frontend:
    type: nodejs:22
    source:
      root: /frontend
    build:
      flavor: none
    hooks:
      build: |
        set -ex
        npm install --omit=dev
        npm run build
    web:
      commands:
        start: npm start
      locations:
        /:
          root: build
          passthru: true
          index: [index.html]
    relationships:
      api-gateway:
        service: "api-gateway"
        endpoint: "http"
    variables:
      env:
        REACT_APP_API_URL: "https://api.{default}/"


routes:
  https://{default}/:
    type: upstream
    upstream: frontend:http
  https://api.{default}/:
    type: upstream
    upstream: api-gateway:http