applications:
  api-gateway:
    type: python:3.11
    source:
      root: api-gateway
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true
    relationships:
      cpu-worker:
        service: "cpu-worker"
        endpoint: "http"
      memory-worker:
        service: "memory-worker"
        endpoint: "http"
      network-simulator:
        service: "network-simulator"
        endpoint: "http"

  cpu-worker:
    type: python:3.11
    source:
      root: cpu-worker
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  memory-worker:
    type: python:3.11
    source:
      root: memory-worker
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  network-simulator:
    type: python:3.11
    source:
      root: network-simulator
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  frontend:
    type: nodejs:20
    source:
      root: frontend
    hooks:
      build: |
        set -ex
        pwd
        ls -la
        ls -la public/
        npm ci
        npm run build
        ls -la build/
    web:
      commands:
        start: npx serve -s build -l 3000
      locations:
        /:
          root: build
          passthru: true
          index: [index.html]
    relationships:
      api-gateway:
        service: "api-gateway"
        endpoint: "http"


routes:
  https://{default}/:
    type: upstream
    upstream: frontend:http
  https://api.{default}/:
    type: upstream
    upstream: api-gateway:http
    id: api