applications:
  api-gateway:
    type: python:3.11
    source:
      root: api-gateway
    hooks:
      build: |
        set -ex
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true
    relationships:
      user-management:
        service: "user-management"
        endpoint: "http"
      payment-processing:
        service: "payment-processing"
        endpoint: "http"
      inventory-system:
        service: "inventory-system"
        endpoint: "http"
      notification-center:
        service: "notification-center"
        endpoint: "http"

  user-management:
    type: python:3.11
    source:
      root: microservices/user-management
    hooks:
      build: |
        set -ex
        # Build microservices from config
        python build_microservices.py
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  payment-processing:
    type: python:3.11
    source:
      root: microservices/payment-processing
    hooks:
      build: |
        set -ex
        # Build microservices from config
        python build_microservices.py
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  inventory-system:
    type: python:3.11
    source:
      root: microservices/inventory-system
    hooks:
      build: |
        set -ex
        # Build microservices from config
        python build_microservices.py
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  notification-center:
    type: python:3.11
    source:
      root: microservices/notification-center
    hooks:
      build: |
        set -ex
        # Build microservices from config
        python build_microservices.py
        pip install -r requirements.txt
    web:
      commands:
        start: python app.py
      locations:
        /:
          passthru: true

  frontend:
    type: nodejs:20
    source:
      root: frontend
    hooks:
      build: |
        set -ex
        pwd
        ls -la
        ls -la public/
        # Don't set REACT_APP_API_URL during build - will be determined at runtime
        echo "Building React app without hardcoded API URL"
        npm ci
        npm run build
        ls -la build/
    web:
      commands:
        start: npx serve -s build -l 3000
      locations:
        /:
          root: build
          passthru: true
          index: [index.html]
    relationships:
      api-gateway:
        service: "api-gateway"
        endpoint: "http"


routes:
  https://{default}/:
    type: upstream
    upstream: frontend:http
  https://api.{default}/:
    type: upstream
    upstream: api-gateway:http
    id: api